### ISSUE TITLE
Submission 1: Number bases and binary search

### ISSUE THREAD

**Issue by Sukhrobjon** [Rediet8abere/CS-1.3-Core-Data-Structures#1]
1. Number base:
Your code works well and passes all the tests, but it is hard to read, if you add comments where you use complex, it makes it easier to read and follow for others and later for you to understand what you did. 
For example this line:
```
frac += str(round(x-int(x), (len(digits)-1) - len(str(int(x)))))
```
Also, instead of mapping all letters to numbers you could have used `ord()` function.
2. Binary search:
The iterative solution is working. but the recursive binary search is failing and throwing `RecursionError: maximum recursion depth exceeded in comparison` this is because you are not checking your bounds. add this line somewhere at the beginning of the recursive binary search.
```
if low > high:
        return None
```
this stops the infinite recursive call.

**Comment by Rediet8abere** [comment]
Thank you for your feedback!
